apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: findfirst
  name: findfirst
spec:
  replicas: 1
  selector:
    matchLabels:
      app: findfirst
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: findfirst
    spec:
      containers:
      - image: frontend
        name: frontend
        resources: {}
status: {}
